### PR TITLE
fix(bam): While the applier configures the ba, there was a segfault

### LINKED ISSUE #164: Wrong bam configuration cause a segfault on broker
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.18

**Centreon Engine version**:  1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Centos 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a bolean rule with a kpi that doesn't not exist anymore
2. Reload the configuration/Restart cbd
3.

**Describe the results you received:**
CBD doesn't start.

**Describe the results you expected:**
CBD start with BAM error but don't have a segfault

**Additional information you think important (e.g. issue happens only occasionally):**
The error message : cbd[193777]: segfault at 0 ip 0000003c1e86f2cc sp 00007f5bfe1f4ea0 error 4 in libQtCore.so.4.7.4[3c1e800000+279000]

### PR DESCRIPTION
**Pull request by bouda1**
This should fix #164 issue.

### CODE REVIEW

File: bam/src/configuration/applier/kpi.cc [hunk 1]
```diff
@@ -141,9 +141,11 @@ void applier::kpi::apply(
   // Delete objects.
   for (std::map<unsigned int, applied>::iterator
          it(to_delete.begin()),
+         next_it(to_delete.begin()),
```
Comment (ganoze) [inline bam/src/configuration/applier/kpi.cc]: IMHO _next_it_ is unnecessary as the _to_delete_ container itself is not modified (and _it_ iterator is not invalidated).

File: bam/src/configuration/applier/kpi.cc [hunk 2]
```diff
@@ -185,8 +187,10 @@ void applier::kpi::apply(
   //
   for (std::map<unsigned int, applied>::const_iterator
          kpi_it(_applied.begin()),
+         next_kpi_it(_applied.begin()),
```
Comment (ganoze) [inline bam/src/configuration/applier/kpi.cc]: Again, neither __resolve_kpi()_ nor __invalidate_ba()_ seem to modify __applied_. So _it_ iterator should be valid, right ?
